### ISSUE TITLE
Top margin for elements for better readability

### ISSUE THREAD

**Issue by awaisanwar544** [ryxtor/Portfolio#10]
- [x] Maybe you can add `margin-top` for headings that would be good for the readability.

<img width="495" alt="Screenshot 2022-01-20 at 7 07 17 PM" src="https://user-images.githubusercontent.com/87834222/150354168-47b10424-647f-4c60-a03c-fc86bbeda7af.png">

- [x] Maybe you changing `cursor` for See Project Button on `hover` would be good

<img width="192" alt="Screenshot 2022-01-20 at 7 13 00 PM" src="https://user-images.githubusercontent.com/87834222/150355308-594ce1c5-a799-4f97-902a-89fe02c8d65a.png">

**Comment by ryxtor** [comment]
All changes are done! ✅  Thanks for the feedback!! 😄
