### ISSUE TITLE
Replace link element tag for buttons element tag on the hamburguer menu and close menu buttons

### ISSUE THREAD

**Issue by helio3197** [ryxtor/Portfolio#12]
I like your page 👍 , it's very clear and responsive, the mobile menu is working well and smoothly, but consider the following:
 

- [x] Why not change the link tag elements from the open menu and close menu buttons for button tag ones, to improve accessibility ✔️

**Comment by ryxtor** [comment]
Fixed! ✅  thank you for the feedback!! 😄
